import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create ({
    container: {
      flex:8,
    },
    logo: {
      position: 'absolute',
      width: 20,
      height: 33.2,
      left: 27,
      top: 29,
    },
    title: {
      position: 'absolute',
      width: 81.18,
      height: 24.66,
      left: 49.52,
      top: 32,
      fontSize: 24,
      fontWeight: 'bold',
      fontStyle: 'italic',
      color: '#FFF',
      textShadowColor: 'rgba(0,0,0,0.25)',
      textShadowOffset: {width: 0, height: 4},
      textShadowRadius: 4,
    },
    messege1Header: {
      position: 'absolute',
      width: 141,
      height: 15,
      left: 20,
      top: 92,
      fontFamily: 'Titillium Web',
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: 14,
      lineHeight: 14,
      textTransform: 'uppercase',
      color: '#FFF',
      textShadowColor: 'rgba(0,0,0,0.25)',
      textShadowOffset: {width: 0, height: 4},
      textShadowRadius: 4,
    },
    messege2Header: {
      position: 'absolute',
      width: 220,
      height: 75,
      left: 21,
      top: 107,
      fontFamily: 'Titillium Web',
      fontStyle: 'normal',
      fontWeight: 'bold',
      fontSize: 36,
      lineHeight: 37,
      textTransform: 'uppercase',
      color: '#FFF',
      textShadowColor: 'rgba(0,0,0,0.25)',
      textShadowOffset: {width: 0, height: 4},
      textShadowRadius: 4,
    },
  });
  